[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"


[project]
name = "solve_ivp_pint"
dynamic = ["version"]
requires-python = ">=3.12"
authors = [
  { name = "Alexandra Loudieres", email = "alexandra.loudieres@ens-paris-saclay.fr" },
  { name = "Matthias Függer", email = "mfuegger@lmf.cnrs.fr" },
  { name = "Thomas Nowak", email = "thomas@thomasnowak.net" },
]
maintainers = [
  { name = "Alexandra Loudieres", email = "alexandra.loudieres@ens-paris-saclay.fr" },
  { name = "Matthias Függer", email = "mfuegger@lmf.cnrs.fr" },
  { name = "Thomas Nowak", email = "thomas@thomasnowak.net" },
]
description = "ODE solver processing pint (using 'solve_ivp' function)"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["ODE solver", "pint", "solve_ivp"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
]
dependencies = ["scipy", "pint"]

[project.urls]
Repository = "https://github.com/BioDisCo/solve_ivp_pint/"

[tool.hatch.version]
source = "vcs"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = [
  "solve_ivp_pint",
] #If the name of the python file containing the code change, it will need to be changed to 


[tool.pyright]
venvPath = "."
venv = "venv"

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 80

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "D401", "D212", "COM812"]

[tool.ruff.lint.per-file-ignores]
"**/examples/*" = ["INP001", "T201"]
"**/tests/**/*" = ["INP001", "PLC1901", "PLR2004", "PLR6301", "S", "TID252"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

